# Relieving the Panic of Hitting Send {#EmailEffectiveness}

#### Keywords {-}

email, recall, oh no, what just happened, panic, wrong recipient, data science for email, lets get smarter

## Oh my God--I cannot believe I just sent that.

Everyone in the corporate world today has made the mistake of hitting send too quickly, or sending the wrong email to the wrong recipient. You desperately try to recall the message scrolling through hundreds of Google articles in about 5 minutes, only to learn that it is nearly impossible [@pinnington_bad_2010]. If all recipients use the same email software as you, and are all within the same company, you may have a shot. Otherwise, your only option is to send a scurried apology email and hope the recipient deleted the sometimes highly confidential information. 

Not only are you not able to recall, emails currently rarely prompt you to fix a potential mistake with a sender name, or even make you aware of large errors before you wind up sending an email. All of a sudden, the financial invoice, new business proposal, or data science model has just gone into the hands of the wrong person, potentially costing the company millions. My idea is to create a new, revolutionary software that allows users to recall messages, analyzes user habits so people can send smarter, more effective emails, and allows corporations to understand employee email habits.

## We have an email solution for you!

Companies and/or individuals can opt into a secure software that can be implemented into all major email software. This add-on will allow users to recall an email from all recipients who have not yet seen the email, and allow users to understand their habits with smart email technology, prompting appropriate word choice and sender names based on email content.

This app will also be able to help companies and individuals be smarter about their emails as well. From an individual perspective, this app will also learn user tendencies and where they may make mistakes. Currently, Gmail and Outlook both have features where if a user writes the word "attached", and nothing is attached to the email, the user gets a reminder. On the same token, if the attachment states the word "Apple", but the user address says "IBM", another important reminder will get fired. 

This software would sort through all of the unstructured data within emails to develop patterns to understand what users say to whom, the tone they take, and their general word choices. The same person would likely send a very different email to a good friend at the company versus a prospective client. The user would also be able to state "yes" or "no" to specific prompts, which would develop a feedback loop, allowing the users individual email technology to get smarter and more customized. Overtime the software would learn user preferences and create built in reminder features such as reminding someone to put a signature when sending to folks where they usually have a signature, or making sure the recipient name at the top of the email matches the email address. [@wong_conspire_2015]

From the company's perspective, this app will monitor email/data usage, size of emails, # of emails per day, etc. so that companies can be smarter about their storage capabilities. Understanding email habits may also help companies implement features like Slack if they see many short emails, informal emails bouncing back and forth. Even moreso, companies will be able to understand how their employees are talking to each other and clients through weekly trend summaries of tone, # of emails, etc. and not specific emails. The "too tough" manager may be able to be pulled aside before the employee complaint or resignation just based on the language that he is using in his emails to subordinates. The "almost defected" client could be managed better as well by making sure that the email language is overly friendly and accomodating. In today's corporate world, all communication matters and being able to communicate smarter and more effectively is imperative to success.

## Our big blunders on email are no more!

Over time, the secure email add-on will help everyone live less worried about mistakes in this new age of hyper email activity, collect data from a company point of view, and help individuals send smarter emails.

A counter-argument could be that users or companies and individuals may be uncomfortable with anything being attached to their email and able to understand the content. Recipients may be anxious about the fact that software can essentially go inside their inbox and remove an email. However, this service would be opted into by a company or individual. While the software would technically be able to "read" email, it will be programmed to help the user and will be personalized over time. Ideally, the service would be a potential add on feater when creating simple email accounts like Gmail or Outlook to make implementation simple.

If many millenials and Gen Xers can be comfortable with online bill pay, mobile device payment transfers, and in depth budgeting apps, this app does not seem like a far stretch. Consumers are learning to trust app security as it helps their lives more and more. Companies or individuals could also set preferences to not have the email add-on for highly confidential information as well. All users will likely come to love the features of this software and the corresponding poka-yolks (mistake-proofing) that come from understanding email habits.
