# My Side of the Story {#MatchMade}

#### Keywords {-}

afraid of commitment, not another dating app, finding my soulmate, making it work, happily never after, date until you drop

## So many dating apps!

Many of those seeking love, long term relationships, or simple companionship have embarked on the dating app quest. As many of us are millennials, we are very comfortable with phone apps and internet technology, even when it comes to our love lives. We start with downloading the app, filling out profiles about ourselves, and then begin the endless swiping, hoping that the same person who we swipe "yes" to likes us back. So often the game we play ends with someone not wanting the same things as we do, or completely ignoring us, which is more commonly referred to now as "ghosting" us, or simply not being compatible. 

What if there were a better way to find out who is right for you? What if there was an app that curated your current matches and future relationships based on who you were in your prior relationships? My idea is for the tons of dating apps including: Tinder, eHarmony, OkCupid, Bumble, PlentyOfFish, Hinge, Happn, Jswipe, Christian Mingle, Grindr, The League, Coffee Meets Bagel, Match.com, Cowboys Nearby, OurTime, and Jdate to become a bit smarter. These apps would have a software add-on that would enable someone to discuss their relationship history, and get matches based off of past relationships.

## A better way to find love.

Many of the dating apps on the market currently match on personality, lifestyle choices, hobbies, interests, etc., but so often a potential predictor to our relationship lifestyle could be past relationships. What effect, if any, do prior relationships have on future ones? My hypothesis is that someone's prior relationships directly impact their future ones, and what they may determine is a successful relationship. This software helps us define the hypothesis by first asking people questions about their relationship history such as number of long-term relationships, why they ended, what they learned, common disagreements, etc. This information would not be frontward facing to potential mates, but simply behind the scenes working with the algorithm already in place in the app to display potential matches. Someone could also choose if they only want to see other individuals that have also opted in to this relationship add-on feature, or if that would not matter to them.

The thought here would be that two people who have both been in long-term relationships may prefer to be matched with other people who have also been in longer relationships. Others that have been in many short-term relationships or are self-proclaimed "commitment phobes" would likely fair far better with people that are not expecting something long-term either. The imbalance of different expectations that could potentially waste a lot of time would no longer be in the way. 

This software would be able to help prove out the hypothesis of past relationships predicting future ones through user feedback. Pretty quickly into dating a new person, it can be fairly obvious what they are looking for, and if they are looking for the same things as you. After a couple of dates, an individual would be prompted within the app or over email to rate their match on relationship expectations. Questions such as, "was this person a good fit for you?" or "were they looking for the same type of relationship as you?" would help us determine if past relationships could be predictors of the future. If someone states that their recent date is in fact a good fit and looking for the same type of relationship, but their date had different prior relationship preferences, past behavior may not predict future relationship behavior. Ideally, we will be able to begin to understand potential predictors of successful relationships though, which could save a lot of time and energy for individuals looking for love in the future.

## Will this really work?

One of the most common points of contention that this new add-on feature may prohibit is the idea that someone may want to pivot. No, they will likely not want to dance or build an excel table, but they may want to pivot from the type of relationship that they have had in the past. Someone may have had many short-term flings or one-night stands in college, and is now looking for something more serious. Or, someone else may have just gotten out of a long-term relationship and is now looking for something more casual. 

Luckily, the software within the app will be able to adapt to user feedback. In fact, the software will encourage user feedback and further curation. If users would like a "pivot" feature and would like to be setup with folks that have had different types of relationships prior, that could work too. Successful relationships out of the potential "pivot" feature could negate our hypothesis of past relationships predicting future ones, but could lead to happy users.

Another inhibitor to this working solution is that consumers lie. Even when nobody is looking over your shoulder to check the information that you put into the dating app, users could still lie over embarrassment or not wanting to be honest with themselves. However, in any data science experiment dealing with vulnerable consumer information, the risk of false information is always apparent. Our hope, is that the quantity will take out some of the noise, and we will still be able to prove or disprove our hypothesis.
